{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "skyhook-agent.serviceAccountName" . }}
  {{- if hasKey .Release "Namespace" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "skyhook-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
